catalog:
  "@antfu/eslint-config": ^5.3.0
  "@types/node": ^24.5.2
  bumpp: ^10.2.3
  c12: ^3.3.0
  citty: ^0.1.6
  consola: ^3.4.2
  eslint: ^9.35.0
  magicast: ^0.3.5
  nypm: ^0.6.2
  tinyexec: ^1.0.1
  tsx: ^4.20.5
  typescript: ^5.9.2
  unbuild: ^3.6.1
  vite: ^7.1.6
  vitest: ^3.2.4
onlyBuiltDependencies:
  - esbuild
